### ISSUE TITLE
Nested inline tag removes spaces from markup

### ISSUE THREAD

**Issue by blvrd** [jordanella/bracelet#2]
I'm starting to test things out with Bracelet and it's looking great! I did run into an problem, though. The example code from the README causes the following behavior:

<img width="434" alt="Screenshot 2024-07-30 at 10 58 52" src="https://github.com/user-attachments/assets/f3019d16-5614-4b53-b131-49ae92c25a28">

As you can see, the semantically meaninful spaces that are present in the markup are removed. Adding margin to the `em` element fixes it:

```go
package main

import (
	"fmt"
	"github.com/jordanella/bracelet"
)

func main() {
	html := `
    <div>
        <h1>Hello, Bracelet!</h1>
        <p>This is a <em>styled</em> paragraph.</p>
    </div>
    `
	css := `
    h1 { color: blue; font-weight: bold; }
    p { margin-left: 2; }
    em { font-style: italic; color: red; margin: 0 1; } // margin added here
    `

	root, _ := bracelet.ParseHTML(html)
	rules, _ := bracelet.ParseCSS(css)
	bracelet.ApplyStylesheet(&root, rules)

	fmt.Println(root.Serve())
}
```
<img width="453" alt="Screenshot 2024-07-30 at 11 01 28" src="https://github.com/user-attachments/assets/2ce814f3-61ba-424f-b2ae-aaeca970da2d">

It's workable but this seems like something that should be handled by the library itself. If you point me in the right direction (I'll start investigating anyway), I'd be happy to look into fixing this myself. I'd love to see this project take over all view-related code in my Bubbletea app!

**Comment by blvrd** [comment]
I _could_ also take the workaround even further by creating a custom `em` node that has that margin by default. Still feels a bit hacky though.

**Comment by jordanella** [comment]
Thank you for raising this issue! I agree that does seems hacky and should work exactly as you'd expect it. I'll take a look at revising the parsing of text if it's interrupted by an inline tag so that way so that it maintains the desired whitespace.

Conversely, I know that whitespace is retained in a manner that doesn't match expected behaviour in an HTML document and it bothered me in situations like this...
```
<p>
    text content
</p>
```

I'll look at addressing both of those as soon as possible and find a more elegant catch all solution.

**Comment by jordanella** [comment]
I've addressed your issue and text spacing behaviour should perform more akin to how you'd expect. This illustrated the issue that inheritance for certain properties such as word-spacing shouldn't just be restricted to text-nodes but that's a new issue! Let me know if there is any unexpected behaviour as a result of this fix.

**Comment by blvrd** [comment]
@jordanella it works as expected now, thanks!
